#!/usr/bin/env bash
# One-command demo deployment of Pension360 on a Linux server (Ubuntu/Debian) with Docker.
#
#   DEMO_LOGIN_ID=demo DEMO_LOGIN_PASSWORD='choose-a-password' \
#   OPENAI_API_KEY='sk-...' OPENAI_MODEL='gpt-...' \
#   bash deploy/server-setup.sh
#
# Run it from the project folder. It is safe to run again to update after a `git pull`.
# This sets up the DEMONSTRATION edition (fictional data, development sign-in protected by
# the login ID and password above). It is not the production/SSO setup.
set -euo pipefail

cd "$(dirname "$0")/.."
SUDO=""
if [ "$(id -u)" -ne 0 ]; then SUDO="sudo"; fi

say() { printf '\n\033[1;34m==> %s\033[0m\n' "$*"; }
rand_hex() { head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'; }

if [ -z "${DEMO_LOGIN_ID:-}" ] || [ -z "${DEMO_LOGIN_PASSWORD:-}" ]; then
  if [ ! -f .env ] || ! grep -q '^DEMO_LOGIN_ID=' .env; then
    echo "Set DEMO_LOGIN_ID and DEMO_LOGIN_PASSWORD (see the top of this script)." >&2
    exit 1
  fi
fi

say "1/6 Docker"
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | $SUDO sh
fi
$SUDO systemctl enable --now docker >/dev/null 2>&1 || true
if ! docker compose version >/dev/null 2>&1 && ! $SUDO docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required (v2.24.4 or newer)." >&2
  exit 1
fi
DOCKER="docker"
if ! docker info >/dev/null 2>&1; then DOCKER="$SUDO docker"; fi

say "2/6 Memory check (the web build needs about 2 GB)"
MEM_MB=$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)
SWAP_MB=$(awk '/SwapTotal/ {print int($2/1024)}' /proc/meminfo)
echo "RAM ${MEM_MB} MB, swap ${SWAP_MB} MB"
if [ $((MEM_MB + SWAP_MB)) -lt 3000 ] && [ ! -f /swapfile ]; then
  echo "Adding a 2 GB swap file so the build does not run out of memory."
  $SUDO fallocate -l 2G /swapfile && $SUDO chmod 600 /swapfile && $SUDO mkswap /swapfile >/dev/null && $SUDO swapon /swapfile
fi

say "3/6 Configuration (.env)"
if [ ! -f .env ]; then
  cp .env.example .env
  PG_PASS=$(rand_hex 24)
  sed -i "s|^POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${PG_PASS}|" .env
  sed -i "s|^DATABASE_URL=.*|DATABASE_URL=postgres://pension360:${PG_PASS}@127.0.0.1:5432/pension360|" .env
  sed -i "s|^DEV_AUTH_SECRET=.*|DEV_AUTH_SECRET=$(rand_hex 48)|" .env
  sed -i "s|^DOCUMENT_ENCRYPTION_KEY=.*|DOCUMENT_ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)|" .env
  echo "Created .env with fresh random secrets."
else
  echo "Keeping your existing .env."
fi
set_var() {
  # set_var NAME VALUE : replace or append NAME=VALUE in .env
  local name="$1" value="$2"
  [ -z "$value" ] && return 0
  if grep -q "^${name}=" .env; then
    local escaped
    escaped=$(printf '%s' "$value" | sed -e 's/[\\&|]/\\&/g')
    sed -i "s|^${name}=.*|${name}=${escaped}|" .env
  else
    printf '%s=%s\n' "$name" "$value" >> .env
  fi
}
set_var DEMO_LOGIN_ID "${DEMO_LOGIN_ID:-}"
set_var DEMO_LOGIN_PASSWORD "${DEMO_LOGIN_PASSWORD:-}"
set_var OPENAI_API_KEY "${OPENAI_API_KEY:-}"
set_var OPENAI_MODEL "${OPENAI_MODEL:-}"
chmod 600 .env

say "4/6 Publish the web port"
cat > compose.server.yml <<'YAML'
# Generated by deploy/server-setup.sh: serve the web app on port 80 of this server.
services:
  web:
    ports: !override ["80:8080"]
YAML

COMPOSE="$DOCKER compose -f compose.yml -f compose.server.yml"

say "5/6 Build and start (the first build takes several minutes)"
$COMPOSE up --build -d

say "6/6 Demo data and health check"
$COMPOSE run --rm --no-deps -e NODE_ENV=development api node apps/api/dist/seed.js || true
for i in $(seq 1 40); do
  if curl -fsS http://127.0.0.1:80/health/ready >/dev/null 2>&1; then
    OK=1; break
  fi
  sleep 3
done
if [ "${OK:-0}" = "1" ]; then
  IP=$(curl -fsS https://api.ipify.org 2>/dev/null || hostname -I | awk '{print $1}')
  printf '\n\033[1;32mPension360 is running.\033[0m Open  http://%s/  (login ID: %s)\n' "$IP" "${DEMO_LOGIN_ID:-see .env}"
  echo "Open TCP port 80 in the server firewall / cloud security group if the page does not load."
else
  echo "The app did not report ready. Check:  $COMPOSE logs --tail 80 api" >&2
  exit 1
fi
